/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CombineRouteImport } from './routes/combine'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioCollectionIdRouteImport } from './routes/studio/$collectionId'
import { Route as StudioNewRouteImport } from './routes/studio/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CombineRoute = CombineRouteImport.update({
  id: '/combine',
  path: '/combine',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCollectionIdRoute = StudioCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => StudioRoute,
} as any)
const StudioNewRoute = StudioNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudioRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combine': typeof CombineRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$collectionId': typeof StudioCollectionIdRoute
  '/studio/new': typeof StudioNewRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combine': typeof CombineRoute
  '/login': typeof LoginRoute
  '/studio/$collectionId': typeof StudioCollectionIdRoute
  '/studio/new': typeof StudioNewRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combine': typeof CombineRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio/$collectionId': typeof StudioCollectionIdRoute
  '/studio/new': typeof StudioNewRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/combine'
    | '/login'
    | '/studio'
    | '/studio/$collectionId'
    | '/studio/new'
    | '/studio/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/combine'
    | '/login'
    | '/studio/$collectionId'
    | '/studio/new'
    | '/studio'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/combine'
    | '/login'
    | '/studio'
    | '/studio/$collectionId'
    | '/studio/new'
    | '/studio/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombineRoute: typeof CombineRoute
  LoginRoute: typeof LoginRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combine': {
      id: '/combine'
      path: '/combine'
      fullPath: '/combine'
      preLoaderRoute: typeof CombineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$collectionId': {
      id: '/studio/$collectionId'
      path: '/$collectionId'
      fullPath: '/studio/$collectionId'
      preLoaderRoute: typeof StudioCollectionIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/new': {
      id: '/studio/new'
      path: '/new'
      fullPath: '/studio/new'
      preLoaderRoute: typeof StudioNewRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioCollectionIdRoute: typeof StudioCollectionIdRoute
  StudioNewRoute: typeof StudioNewRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioCollectionIdRoute: StudioCollectionIdRoute,
  StudioNewRoute: StudioNewRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombineRoute: CombineRoute,
  LoginRoute: LoginRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
